<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">手机号:</label>
                        <div class="layui-input-inline">
                            <input name="phone" class="layui-input" placeholder="输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">时间</label>
                        <div class="layui-input-inline">
                            <input name="start_time" id="start_time" value="<?php echo date("Y-m-d H:i:s", \App\Utils\CommonUtil::getTodayZeroTime()); ?>" class="layui-input date"
                                   placeholder="开始时间"/>
                        </div>

                        <label class="layui-form-label">~</label>
                        <div class="layui-input-inline">
                            <input name="end_time" id="end_time" value="<?php echo date("Y-m-d H:i:s", \App\Utils\CommonUtil::getTodayEndTime()); ?>" class="layui-input date" placeholder="结束时间"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
        </div>
    </div>
</div>
<script>
    var layerIndex, layer, table, form, laydate, $;
    layui.use(['layer', 'form', 'table', 'admin', 'laydate'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;
        laydate = layui.laydate;

        /*初始化表格*/
        table.render({
            elem: '#table'
            , url: location.href
            , method: "post"
            , where: form.val("searchForm")
            , skin: 'line'
            , size: 'sm' //小尺寸的表格
            , toolbar: '#table-toolbar'
            , request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            , page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                , curr: 1 //设定初始在第 1 页
                , groups: 6 //只显示 5 个连续页码
                , first: '首页'
                , last: '尾页'
                , limit: 30
                , limits: [10, 30, 50, 100]
            }
            , parseData: function (res) { //res 即为原始返回的数据
                return res;
            }
            , cols: [[
                {type: 'checkbox'}
                , {field: '_id', title: 'ID', align: 'center', width: 100, sort: true}
                , {field: 'country', title: '国家', align: 'center'}
                , {field: 'phone', title: '手机号', align: 'center'}
                , {field: 'content', title: '内容', align: 'center'}
                , {field: 'error_info', title: '错误信息', align: 'center'}
                , {field: 'ip', title: 'IP', align: 'center'}
                , {field: 'created_at', title: '发送时间', align: 'center', sort: true}
            ]],
        });
        laydate.render({
            elem: '#start_time'//指定元素
            , trigger: 'click'
            , type: 'datetime'
        });
        laydate.render({
            elem: '#end_time'//指定元素
            , trigger: 'click'
            , type: 'datetime'
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function (obj) {
            table.reload('table', {where: obj.field, page: {curr: 1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function (obj) {
            var order = obj.type === 'asc' ? 1 : -1;
            table.reload('table', {initSort: obj, where: {sort: obj.field, order: order}});
        });
    })
</script>
