<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">渠道码:</label>
                        <div class="layui-input-inline">
                            <input name="channel_name" class="layui-input" autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>

                    <div class="layui-inline">
                        <label class="layui-form-label">时间范围:</label>
                        <div class="layui-input-inline">
                            <input type="text" name="start_time" id="laydate-start-at" value="<?php echo date("Y-m-d"); ?>" placeholder="yyyy-mm-dd H:i:s" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline">
                            <input type="text" name="end_time" id="laydate-end-at" value="<?php echo date("Y-m-d"); ?>" placeholder="yyyy-mm-dd H:i:s" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <!--                    <button class="layui-btn layui-btn-xs" lay-event="up">启用</button>-->
                    <!--                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="down">禁用</button>-->
                    <!--                    <button class="layui-btn layui-btn-xs" lay-event="add">添加</button>-->
                    <!--                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>-->
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex, layer, table, form, laydate, $;
    layui.use(['layer', 'form', 'table', 'admin', 'laydate'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;
        laydate = layui.laydate;

        /*初始化表格*/
        table.render({
            elem: '#table'
            , url: location.href
            , method: "post"
            , where: form.val("searchForm")
            , skin: 'line'
            , size: 'sm' //小尺寸的表格
            , toolbar: '#table-toolbar'
            , request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            , page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                , curr: 1 //设定初始在第 1 页
                , groups: 6 //只显示 5 个连续页码
                , first: '首页'
                , last: '尾页'
                , limit: 30
                , limits: [10, 30, 50, 100, 500, 1000, 3000]
            }
            , totalRow: true
            , parseData: function (res) { //res 即为原始返回的数据
                return res;
            }
            , cols: [[
                // {type: 'checkbox'},
                {field: 'channel_name', title: '渠道码', width: 100, align: 'center'},
                {field: 'date', title: '日期', width: 100, align: 'center', sort: true},
                {
                    field: 'reg', title: '新增', templet: function (row) {
                        var html = '';
                        html += '<span style="color:red">合计: ' + row.reg + '</span><br/>';
                        html += '<span>安卓: ' + row.reg_android + '</span><br/>';
                        html += '<span>IOS: ' + row.reg_ios + '</span><br/>';
                        html += '<span>WEB: ' + row.reg_web + '</span><br/>';
                        return html;
                    }, align: 'left',sort: true,
                },
                {
                    field: 'amount', title: '充值', templet: function (row) {
                        var html = '';
                        html += '<span style="color:red">合计: ' + row.amount + '</span><br/>';
                        html += '<span >会员: ' + row.order_amount + '</span><br/>';
                        html += '<span >金币: ' + row.recharge_amount + '</span><br/>';
                        return html;
                    }, align: 'left'
                },
                {
                    field: 'daot', title: '平均在线时长', templet: function (row) {
                        var html = '';
                        html += '<span style="color:red">总: ' + row.daot + '</span><br/>';
                        html += '<span >安卓: ' + row.daot_android + '</span><br/>';
                        html += '<span >IOS: ' + row.daot_ios + '</span><br/>';
                        html += '<span >WEB: ' + row.daot_web + '</span><br/>';
                        return html;
                    }, align: 'left'
                },
                {field: 'ip', title: 'IP', align: 'center', width: 80, sort: true},
                {field: 'uv', title: 'UV', align: 'center', width: 80, sort: true},
                {field: 'pv', title: 'PV', align: 'center', width: 80, sort: true},
                {field: 'adv', title: '广告点击', align: 'center', sort: true},
                {field: 'adv_app', title: '应用点击', align: 'center', sort: true},
                {field: 'dau_0', title: '当日日活', align: 'center', sort: true},
                {field: 'dau_1', title: '次日日活', align: 'center', sort: true},
                {field: 'dau_3', title: '3日日活', align: 'center', sort: true},
                {field: 'dau_5', title: '5日日活', align: 'center', sort: true},
                {field: 'dau_7', title: '7日日活', align: 'center', sort: true},
                // {field: 'dau_15', title: '15日日活', align: 'center', sort: true},
                {
                    field: 'agent_v3', title: 'V3当日统计', templet: function (row) {
                        var html = '';
                        if(row.agent_v3){
                            html += '<span>ip:' + row.agent_v3.ip + '</span><br/>';
                            html += '<span>pv:' + row.agent_v3.pv + '</span><br/>';
                            html += '<span>uv:' + row.agent_v3.uv + '</span><br/>';
                            html += '<span>安卓点击:' + row.agent_v3.click_android + '</span><br/>';
                            html += '<span>IOS点击:' + row.agent_v3.click_ios + '</span><br/>';
                            html += '<span>总新增:' + row.agent_v3.total_user_reg + '</span><br/>';
                            html += '<span>安卓新增:' + row.agent_v3.total_android_user_reg + '</span><br/>';
                            html += '<span>IOS新增:' + row.agent_v3.total_ios_user_reg + '</span><br/>';
                            html += '<span>累计充值:' + row.agent_v3.total_order_money + '</span><br/>';
                            html += '<span>今日充值:' + row.agent_v3.today_order_money + '</span><br/>';
                            html += '<span>1日留存:' + row.agent_v3.urr_1 + '</span><br/>';
                            html += '<span>3日留存:' + row.agent_v3.urr_3 + '</span><br/>';
                            html += '<span>7日留存:' + row.agent_v3.urr_7 + '</span><br/>';
                        }
                        return html;
                    }, align: 'left'
                },
                {field: 'updated_at', title: '统计时间', width: 120},
            ]],
        });
        laydate.render({
            elem: '#laydate-start-at'//指定元素
            , trigger: 'click'
            , type: 'date'
        });
        laydate.render({
            elem: '#laydate-end-at'//指定元素
            , trigger: 'click'
            , type: 'date'
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function (obj) {
            table.reload('table', {where: obj.field, page: {curr: 1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function (obj) {
            var order = obj.type === 'asc' ? 1 : -1;
            table.reload('table', {initSort: obj, where: {sort: obj.field, order: order}});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function (obj) {
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for (var index = 0; index < data.length; index++) {
                if (data[index].channel_id) {
                    ids.push(data[index].channel_id)
                }
            }
            switch (obj.event) {

            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function (obj) {
            var data = obj.data;
            switch (obj.event) {
                case 'edit':

                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    // doRow(ids,'del');
                    break;
            }
        });

        function doRow(ids, act) {
            if (ids == null || ids.length < 1) {
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?", function () {
                var loadIndex = layer.load(0, {time: 30 * 1000});
                doAjax("<?php echo url()->get('/channel/do')?>", {act: act, id: ids.join(",")}, function (res) {
                    layer.close(loadIndex);
                    if (res.status == 'y') {
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    } else {
                        showErrorMsg(res.error);
                    }
                });
            });
        }
    })
</script>
