<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">菜单详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id" placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称:</label>
                            <div class="layui-input-block">
                                <input type="text" name="name" lay-verify="required" placeholder="" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">标识:</label>
                            <div class="layui-input-block">
                                <input type="text" name="code" placeholder="唯一标识,首页固定home" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item" pane="">
                            <label class="layui-form-label layui-form-required">板块:</label>
                            <div class="layui-input-block">
                                <?php foreach ($posArr as $key => $value): ?>
                                    <input type="radio" name="position" value="<?php echo $key; ?>" lay-skin="primary" title="<?php echo $key . ' | ' . $value; ?>">
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">样式:</label>
                            <div class="layui-input-block">
                                <select name="style" lay-verType="tips" lay-verify="required" required>
                                    <option value="">请选择..</option>
                                    <?php foreach ($styleArr as $key => $value): ?>
                                        <option value="<?php echo $key; ?>"><?php echo $key . ' | ' . $value; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">搜索条件:</label>
                            <div class="layui-input-block">
                                <textarea name="filter" rows="3" class="layui-textarea" placeholder="请输入json格式搜索条件"></textarea>
                                <div class="layui-word-aux">
                                    <p>模块模式下不用输入</p>
                                    <p>列表模式-纯列表 必须输入,格式同模块内的搜索条件一样</p>
                                    <p>列表模式-tab+列表 必须输入,格式必须为数组,例: [{"name":"二次元","filter":{}},{"name":"二次元","filter":{}}]  其中filter为具体搜索条件,搜索条件参考模块,可寻求技术指导</p>
                                </div>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">排序:</label>
                            <div class="layui-input-block">
                                <input type="number" name="sort" class="layui-input" value="0" lay-skin="primary" placeholder="请输入排序值">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">SEO标题:</label>
                            <div class="layui-input-block">
                                <input type="text" name="seo_title" class="layui-input" placeholder="请输入SEO标题">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">SEO关键字:</label>
                            <div class="layui-input-block">
                                <input type="text" name="seo_keywords" class="layui-input" placeholder="请输入SEO关键字">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">SEO描述:</label>
                            <div class="layui-input-block">
                                <input type="text" name="seo_description" class="layui-input" placeholder="请输入SEO描述">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">是否禁用:</label>
                            <div class="layui-input-block">
                                <input name="is_disabled" type="radio" value="0" title="启用" checked/>
                                <input name="is_disabled" type="radio" value="1" title="禁用"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form', 'upload'], function () {
        var $ = layui.$
            , element = layui.element
            , upload = layui.upload
            , form = layui.form;
        form.val('info-form',<?php echo json_encode($row);?>);
        form.render(null, 'info-form');
        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function (obj) {
            var loadIndex = layer.load(0, {time: 30 * 1000});
            doAjax("<?php echo url()->get('/audioNav/save')?>", obj.field, function (res) {
                layer.close(loadIndex);
                if (res.status === 'y') {
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

        form.on('radio(radio-style)', function (data) {  //radio-type为lay-filter的属性值

        });
    });
</script>
