<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">

                    <div class="layui-inline">
                        <label class="layui-form-label">弹幕ID:</label>
                        <div class="layui-input-inline">
                            <input name="_id" value="" class="layui-input" autocomplete="off" placeholder="请输入弹幕ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label"><?php echo $object_title; ?>ID:</label>
                        <div class="layui-input-inline">
                            <input name="object_id" value="<?php echo $object_id ?: ''; ?>" class="layui-input" autocomplete="off" placeholder="请输入资源ID"/>
                        </div>
                    </div>

                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" value="" class="layui-input" autocomplete="off" placeholder="请输入用户ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">内容:</label>
                        <div class="layui-input-inline">
                            <input name="content" value="" class="layui-input" autocomplete="off" placeholder="请输入弹幕内容"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status">
                                <option value="">请选择..</option>
                                <?php foreach ($statusArr as $key => $item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>

                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="delAndDis">删除+禁用</button>
                    <button class="layui-btn layui-btn-xs" lay-event="pass">审核通过</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="pass">审核通过</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex, layer, table, form, $;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;

        /*初始化表格*/
        table.render({
            elem: '#table'
            , url: location.href
            , method: "post"
            , where: form.val("searchForm")
            , skin: 'line'
            , size: 'sm' //小尺寸的表格
            , toolbar: '#table-toolbar'
            , request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            , page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                , curr: 1 //设定初始在第 1 页
                , groups: 6 //只显示 5 个连续页码
                , first: '首页'
                , last: '尾页'
                , limit: 50
                , limits: [10, 30, 50, 100]
            }
            , parseData: function (res) { //res 即为原始返回的数据
                return res;
            }
            , cols: [[
                {type: 'checkbox'}
                , {field: '_id', title: 'ID', align: 'center', sort: true, width: 150}
                , {
                    field: '_id', width: 100, title: '用户ID', templet: function (row) {
                        return "<p>ID: " + row.user._id + "</p>" +
                            "<p>用户名: " + row.user.username + "</p>" +
                            "<p>语言: " + row.user.lang + "</p>";
                    }, align: 'left'
                }

                , {
                    field: 'nickname', title: '昵称', width: 130, templet: function (row) {
                        var html = '';
                        html += '<span>昵称:' + row.user.nickname + '</span><br/>';
                        html += '<span>性别:' + row.user.sex + '</span><br/>';
                        html += '<span>会员:' + row.user.group_name + '</span><br/>';
                        if (row.user.is_up) {
                            html += '<span style="color: red">Up主:是</span><br/>';
                        } else {
                            html += '<span>Up主:否</span><br/>';
                        }
                        return html;
                    }, align: 'left'
                }
                , {field: 'object_id', title: '<?php echo $object_title;?>ID', align: 'center', width: 100, sort: true}
                , {
                    field: 'content', title: "弹幕内容", align: 'center', width: 300, templet: function (item) {
                        var html = '';
                        html += '<p class="message-text">' + item.content + '</p>'
                        return html;
                    }
                }
                , {field: 'status_text', title: "状态", align: 'center'}
                , {field: 'created_at', title: "创建时间", align: 'center', sort: true}
                ,{title:'操作'/*, toolbar: '#table-item-toolbar'*/,align: 'center', width: 150,templet:function (row) {
                        var html = '';
                        if(row.status==0){
                            html += '<a class="layui-btn layui-btn-xs" lay-event="pass">审核通过</a>';
                        }
                        html += '<a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</a>';
                        return html;
                    }}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function (obj) {
            table.reload('table', {where: obj.field, page: {curr: 1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function (obj) {
            var order = obj.type === 'asc' ? 1 : -1;
            table.reload('table', {initSort: obj, where: {sort: obj.field, order: order}});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function (obj) {
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for (var index = 0; index < data.length; index++) {
                ids.push(data[index]._id)
            }
            switch (obj.event) {
                case 'del':
                    doRow(ids, 'del');
                    break;
                case 'delAndDis':
                    doRow(ids, 'delAndDis');
                    break;
                case 'pass':
                    doRow(ids, 'pass');
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function (obj) {
            var data = obj.data;
            switch (obj.event) {
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids, 'del');
                    break;
                case 'pass':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids, 'pass');
                    break;
            }
        });

        function doRow(ids, act) {
            if (ids == null || ids.length < 1) {
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?", function () {
                var loadIndex = layer.load(0, {time: 30 * 1000});
                doAjax("<?php echo url()->get('/danmaku/do')?>", {act: act, id: ids.join(",")}, function (res) {
                    layer.close(loadIndex);
                    if (res.status == 'y') {
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    } else {
                        showErrorMsg(res.error);
                    }
                });
            });
        }
    })
</script>
