<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">活动ID:</label>
                        <div class="layui-input-inline">
                            <input name="activity_id" class="layui-input" placeholder="输入活动ID"/>
                        </div>
                    </div>

                    <div class="layui-inline">
                        <label class="layui-form-label">订单号:</label>
                        <div class="layui-input-inline">
                            <input name="order_sn" class="layui-input" placeholder="输入订单号"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">抽奖时间:</label>
                        <div class="layui-input-inline">
                            <input type="text" name="start_time" id="laydate-start-at" placeholder="yyyy-mm-dd H:i:s" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-input-inline">
                            <input type="text" name="end_time" id="laydate-end-at" placeholder="yyyy-mm-dd H:i:s" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input" placeholder="输入用户ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户名:</label>
                        <div class="layui-input-inline">
                            <input name="username" class="layui-input" placeholder="输入用户名"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex, layer, table,laydate, form, $;
    layui.use(['layer', 'form', 'table', 'admin','laydate'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;
        laydate = layui.laydate;

        /*初始化表格*/
        table.render({
            elem: '#table'
            , url: location.href
            , method: "post"
            , where: form.val("searchForm")
            , skin: 'line'
            , size: 'sm' //小尺寸的表格
            , toolbar: '#table-toolbar'
            , request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            , page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                , curr: 1 //设定初始在第 1 页
                , groups: 6 //只显示 5 个连续页码
                , first: '首页'
                , last: '尾页'
                , limit: 30
                , limits: [10, 30, 50, 100]
            }
            , parseData: function (res) { //res 即为原始返回的数据
                return res;
            }
            , cols: [[
                // {type: 'checkbox'}
                 {field: '_id', title: 'ID', align: 'center'}
                , {field: 'order_sn', title: '订单号', align: 'center'}
                , {field: 'user_id', title: '用户ID', align: 'center'}
                , {field: 'username', title: '用户名', align: 'center'}
                , {field: 'prize_name', title: '奖品名称', align: 'center'}
                , {field: 'prize_type', title: '奖品类型', align: 'center'}
                , {
                    field: 'content', title: '奖品图片', align: 'center', templet: function (row) {
                        if(row.prize_image){
                            var link = '<?php echo $mediaUrl;?>' + row.prize_image;
                            return '<a target="_blank" href="' + link + '" ><img src="' + link + '" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 30px;max-height: 25px"/></a>'
                        }
                        return '-';
                    }, width: 120
                }
                , {field: 'prize_rate', title: '奖品概率', align: 'center'}
                , {field: 'cost_model', title: '消耗类型', align: 'center'}
                , {field: 'cost_value', title: '消耗值', align: 'center'}
                , {field: 'created_at', title: '创建时间', align: 'center', width: 120}
                // , {title: '操作', toolbar: '#table-item-toolbar', align: 'center', width: 150}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function (obj) {
            table.reload('table', {where: obj.field, page: {curr: 1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function (obj) {
            var order = obj.type === 'asc' ? 1 : -1;
            table.reload('table', {initSort: obj, where: {sort: obj.field, order: order}});
        });

        laydate.render({
            elem: '#laydate-start-at'
            , type: 'datetime'
        });
        laydate.render({
            elem: '#laydate-end-at'
            , type: 'datetime'
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function (obj) {
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for (var index = 0; index < data.length; index++) {
                ids.push(data[index]._id)
            }
            switch (obj.event) {
                case 'add_lottery':
                    layerIndex = layer.open({
                        type: 2,
                        content: "<?php echo url()->get('/activity/detail'); ?>?tpl_id=lottery",
                        area: ['80%', '90%']
                    });
                    break;
                case 'del':
                    doRow(ids, 'del');
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function (obj) {
            var data = obj.data;
            switch (obj.event) {
                case 'edit':
                    layerIndex = layer.open({
                        type: 2,
                        content: "<?php echo url()->get('/activity/detail'); ?>?_id=" + data._id,
                        area: ['80%', '90%']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids, 'del');
                    break;
            }
        });

        function doRow(ids, act) {
            if (ids == null || ids.length < 1) {
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?", function () {
                var loadIndex = layer.load(0, {time: 30 * 1000});
                doAjax("<?php echo url()->get('/activity/do')?>", {act: act, id: ids.join(",")}, function (res) {
                    layer.close(loadIndex);
                    if (res.status == 'y') {
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    } else {
                        showErrorMsg(res.error);
                    }
                });
            });
        }
    })
</script>
