<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">提现方式:</label>
                        <div class="layui-input-inline">
                            <select name="method">
                                <option value="">请选择..</option>
                                <?php foreach ($methodArr as $value => $label): ?>
                                    <option value="<?php echo $value; ?>"><?php echo $label; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status">
                                <option value="">请选择..</option>
                                <?php foreach ($statusArr as $value => $label): ?>
                                    <option value="<?php echo $value; ?>"><?php echo $label; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID:</label>
                        <div class="layui-input-inline">
                            <input name="user_id" class="layui-input" placeholder="输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">开始时间:</label>
                        <div class="layui-input-inline">
                            <input name="start_time"  id="start_time" class="layui-input icon-date" placeholder="开始时间"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">结束时间:</label>
                        <div class="layui-input-inline">
                            <input name="end_time" id="end_time" class="layui-input icon-date" placeholder="结束时间"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
<!--                    <button class="layui-btn layui-btn-xs" lay-event="add">添加</button>-->
<!--                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>-->
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
<!--                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>-->
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex,layer,table,form,$;
    layui.use(['layer', 'form', 'table', 'admin','laydate'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;
        laydate = layui.laydate;

        /*初始化表格*/
        table.render({
            elem: '#table'
            ,url: location.href
            ,method: "post"
            ,where: form.val("searchForm")
            ,skin:'line'
            ,size: 'sm' //小尺寸的表格
            // ,toolbar: '#table-toolbar'
            ,request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                ,curr: 1 //设定初始在第 1 页
                ,groups: 6 //只显示 5 个连续页码
                ,first: '首页'
                ,last: '尾页'
                ,limit:30
                ,limits:[10,30,50,100]
            }
            ,parseData: function(res){ //res 即为原始返回的数据
                return res;
            }
            ,cols: [[
                {field: '_id', title: '编号',align: 'center',width:100,   sort:true},
                {field: 'nickname', title: '用户信息',width:150,templet:function (row) {
                        var html = '';
                        html += '<span>ID: '+row.user_id+'</span><br/>';
                        html += '<span>昵称: '+row.nickname+'</span><br/>';
                        if(row.is_up=='y'){
                            html += '<span style="color: red">Up主: 是</span><br/>';
                        }else {
                            html += '<span>Up主: 否</span><br/>';
                        }
                        html += '<span>禁用: '+row.is_disabled+'</span><br/>';
                        return html;
                    },align: 'left'},
                {field: 'num', title: '金额信息',width:150,templet:function (row) {
                        var html = '';
                        html += '<span>提现: '+row.num+'</span><br/>';
                        html += '<span>手续费: '+row.fee+'</span><br/>';
                        html += '<span style="color: red">实际到账: '+row.actual_amount+'</span><br/>';
                        return html;
                    },align: 'left'},
                {field: 'method', title: '收款信息',templet:function (row) {
                        var html = '';
                        html += '<span style="color: #00a0e9">收款方式: '+row.method_text+'</span><br/>';
                        html += '<span>收款方姓名: '+row.account_name+'</span><br/>';
                        html += '<span>收款方账号: '+row.account+'</span><br/>';
                        html += '<span>收款方银行: '+row.bank_name+'</span><br/>';
                        return html;
                    },align: 'left'},
                {field: 'ip', title: 'IP',  width: 170,templet:function (row) {
                    return "<p>IP:"+row.ip+"</p>"+"<p>位置:"+(row.address)+"</p>"
                }, align: 'center'},
                {field: 'status_text', title: '状态',align: 'center',  width: 90},
                {field: 'created_at',align: 'center',  title: '创建时间',width: 130, sort:true},
                {field: 'updated_at',align: 'center',  title: '更新时间',width: 130, sort:true},
                {title:'操作', toolbar: '#table-item-toolbar',align: 'center', width:120}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function(obj){
            table.reload('table',{where:obj.field,page:{curr:1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function(obj){
            var order=obj.type==='asc'?1:-1;
            table.reload('table', {initSort: obj,where: {sort: obj.field,order: order }});
        });
        /*表格-行事件*/
        table.on('tool(table)', function(obj){
            var data = obj.data;
            switch (obj.event) {
                case 'edit':
                    layerIndex=layer.open({
                        type: 2,
                        content: "<?php echo url()->get('/userWithdraw/detail'); ?>?_id="+data._id,
                        area:  ['85%', '90%']
                    });
                    break;
            }
        });
        //日期时间选择器
        laydate.render({
            elem: '#start_time'
            ,type: 'datetime'
        });
        laydate.render({
            elem: '#end_time'
            ,type: 'datetime'
        });
    })
</script>
