<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">文章详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id" placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">标题:</label>
                            <div class="layui-input-block">
                                <input name="title" placeholder="请输入标题" class="layui-input" lay-verType="tips"
                                       lay-verify="required" required/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">分类</label>
                            <div class="layui-input-block">
                                <select name="category_code" lay-verType="tips" lay-verify="required" required>
                                    <option value="">请选择..</option>
                                    <?php echo $catOptions; ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">是否推荐:</label>
                            <div class="layui-input-block">
                                <input name="is_recommend" type="radio" value="0" title="否" checked/>
                                <input name="is_recommend" type="radio" value="1" title="是"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">内容:</label>
                            <div class="layui-input-block">
                                <div id="content"></div>
<!--                                <textarea name="content" lay-verType="tips" lay-verify="required" required id="contentEditor" style="height: 350px" class="layui-textarea editer-text"></textarea>-->
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="输入排序" class="layui-input" type="number" value="0"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">点击次数:</label>
                            <div class="layui-input-block">
                                <input name="click" placeholder="输入点击次数" class="layui-input" type="number" value="0"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">跳转URL:</label>
                            <div class="layui-input-block">
                                <input name="url" placeholder="输入跳转URL" class="layui-input" value=""/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">发布时间:</label>
                            <div class="layui-input-block">
                                <input name="created_at" class="layui-input" id="laydate-created_at" placeholder="yyyy-MM-dd HH:mm:ss" value=""/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/admin/default/assets/libs/wangeditor/wangEditor.min.js"></script>
<script>
    const E = window.wangEditor;
    const editor = new E('#content');
    layui.use(['index', 'form', 'laydate'], function () {
        var $ = layui.$
            , element = layui.element
            , laydate = layui.laydate
            , form = layui.form;
        form.val('info-form',<?php echo json_encode($row);?>);
        laydate.render({
            elem: '#laydate-created_at'
            , type: 'datetime'
        });
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        form.on('submit(info-form)', function(obj){
            var loadIndex=layer.load(0,{time: 30*1000});
            obj.field.content=editor.txt.html();
            doAjax("<?php echo url()->get('/article/save')?>",obj.field,function (res) {
                layer.close(loadIndex);
                if(res.status==='y'){
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });
        initEditor();
    });

    function initEditor() {
        editor.config.height = 400;
        editor.config.menus = ['head','link','bold','underline','italic','strikeThrough','indent','foreColor','justify','emoticon'];
        editor.create();
        editor.txt.html(`<?php echo $row['content']??'';?>`);
    }
</script>
