<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">应用详情</div>
                <div class="layui-card-body">
                    <form class="layui-form" action="" lay-filter="info-form">
                        <input type="hidden" name="_id" placeholder="" autocomplete="off" class="layui-input">

                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">名称:</label>
                            <div class="layui-input-block">
                                <input name="name" placeholder="请输入应用名称" class="layui-input" autocomplete="off" lay-verify="required"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">图片:</label>
                            <div class="layui-input-block">
                                <div id="imgX" class="user-tag upload-select-picture-card">
                                    <span class="layui-icon layui-icon-addition"></span>
                                </div>
                                <input name="image" id="imgXInput" value="" type="text" class="layui-input" style="display: none"/>
                            </div>
                        </div>
                        <div class="layui-form-item" pane="">
                            <label class="layui-form-label layui-form-required">分组:</label>
                            <div class="layui-input-block">
                                <?php foreach ($posArr as $key => $value): ?>
                                    <input type="checkbox" name="position[]" <?php if($row['position']&&in_array($key,$row['position'])):?>checked<?php endif;?>  value="<?php echo $key;?>" lay-skin="primary" title="<?php echo $key . ' | ' . $value;?>">
                                <?php endforeach;?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label layui-form-required">下载地址:</label>
                            <div class="layui-input-block">
                                <input name="download_url" placeholder="请输入" autocomplete="off" class="layui-input" lay-verify="required"/>
                                <div class="layui-word-aux">
                                    <?php foreach ($protocolArr as $key=>$item):?>
                                        <p><?php echo $key.': '.$item;?></p>
                                    <?php endforeach;?>
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">下载次数:</label>
                            <div class="layui-input-block">
                                <input name="download" value="0" placeholder="请输入" autocomplete="off" class="layui-input" lay-verify="required"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label ">排序:</label>
                            <div class="layui-input-block">
                                <input name="sort" placeholder="请输入排序" value="0" autocomplete="off" class="layui-input" lay-verify="required|number"/>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">描述:</label>
                            <div class="layui-input-block">
                                <textarea name="description" class="layui-textarea" autocomplete="off"></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">热门</label>
                            <div class="layui-input-block">
                                <?php foreach ($hotArr as $key => $item): ?>
                                    <input type="radio" name="is_hot" value="<?php echo $key; ?>" title="<?php echo $item; ?>" <?php if ($key == 0): ?>checked<?php endif ?> >
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">禁用</label>
                            <div class="layui-input-block">
                                <?php foreach ($disArr as $key => $item): ?>
                                    <input type="radio" name="is_disabled" value="<?php echo $key; ?>" title="<?php echo $item; ?>" <?php if ($key == 0): ?>checked<?php endif ?> >
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="info-form">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index', 'form', 'upload'], function () {
        var $ = layui.$
            , element = layui.element
            , upload = layui.upload
            , form = layui.form
            , row = <?php echo json_encode($row);?>;

        form.val('info-form', row);
        form.render(null, 'info-form');

        element.render('breadcrumb', 'breadcrumb');

        //回显部分数据
        if (row && row.image) {
            $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>" + row.image + "'>");
        }

        //上传图片
        upload.render({
            elem: '#imgX' //绑定元素
            , url: '<?php echo $uploadUrl; ?>' //上传接口
            , before: function (obj) {
                layer.load(0, {time: 30 * 1000});
            }
            , done: function (res) {
                layer.closeAll('loading');
                if (res.status == 'y') {
                    $("#imgX").html("<img width='102' height='102' src='<?php echo $mediaUrl;?>" + res.data + "'>");
                    $("#imgXInput").val(res.data);
                } else {
                    showErrorMsg(res.error)
                }
            }
            , error: function () {
                //请求异常回调
                showErrorMsg('上传异常')
            }
        });

        form.on('submit(info-form)', function (obj) {
            var loadIndex = layer.load(0, {time: 30 * 1000});
            doAjax("<?php echo url()->get('/advApp/save')?>", obj.field, function (res) {
                layer.close(loadIndex);
                if (res.status === 'y') {
                    showSuccessMsg("保存成功!");
                    parent.layer.close(parent.layerIndex);
                    parent.table.reload('table');
                    return;
                }
                showErrorMsg(res.error);
            });
            return false;
        });

    });
</script>
