<style>
    .layui-margin-top {
        margin-top: 6px;
        margin-bottom: 6px;
    }
</style>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header system-main-nav">搜索</div>
        <div class="layui-card-body">
            <form class="layui-form toolbar" lay-filter="searchForm">
                <div class="layui-form-item">
                    <div>
                        <input type="hidden" name="tags" id="tag" value="">
                        <?php foreach ($tagArr as $group => $tag): ?>
                            <div class="layui-row">
                                <div class="layui-col-md">
                                    <label class="layui-form-label"><?php echo $group; ?>:</label>
                                </div>
                                <div style="display: flex;flex-wrap: wrap;margin-top: 3px;">
                                    <?php foreach ($tag as $item): ?>
                                        <button style="margin:6px 12px 6px 0;" lay-active="tag" data-id="<?php echo $item['id']; ?>" type="button"
                                                class="layui-btn layui-margin-top layui-btn-sm-tag layui-btn-primary layui-btn-sm"><?php echo $item['id'] . " | " . $item['name']; ?></button>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <hr class="layui-border-black">
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">分类:</label>
                        <div class="layui-input-inline">
                            <select name="cat_id" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($catArr as $key => $item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">购买:</label>
                        <div class="layui-input-inline">
                            <select name="pay_type" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($payTypeArr as $key => $item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">状态:</label>
                        <div class="layui-input-inline">
                            <select name="status" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($statusArr as $key => $item): ?>
                                    <option value="<?php echo $key; ?>" <?php if ($key == $defaultStatus) {
                                        echo 'selected';
                                    }; ?>><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">更新状态:</label>
                        <div class="layui-input-inline">
                            <select name="update_status" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($updateStatusArr as $key => $item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">角标:</label>
                        <div class="layui-input-inline">
                            <select name="icon" lay-search>
                                <option value="">请选择..</option>
                                <?php foreach ($iconArr as $key => $item): ?>
                                    <option value="<?php echo $key; ?>"><?php echo $item; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">观看范围:</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="clickMinSort" placeholder="最小值" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="clickMaxSort" placeholder="最大值" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">收藏率范围:</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="favMinSort" placeholder="最小值" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="favMaxSort" placeholder="最大值" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">排序范围:</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="minSort" placeholder="最小值" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="maxSort" placeholder="最大值" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">ID:</label>
                        <div class="layui-input-inline">
                            <input name="_id" class="layui-input" autocomplete="off" placeholder="请输入ID"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">名称:</label>
                        <div class="layui-input-inline">
                            <input name="name" class="layui-input" autocomplete="off" placeholder="请输入名称"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">更新表:</label>
                        <div class="layui-input-inline">
                            <input name="update_date" class="layui-input" autocomplete="off" placeholder="请输入更新表"/>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layui-btn-sm" lay-submit="" lay-filter="searchFormBtn">搜索</button>
                        <button type="reset" class="layui-btn layui-btn-sm layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
            <!-- 数据表格 -->
            <table class="layui-hide" id="table" lay-filter="table"></table>
            <!-- 数据表格-顶部工具条 -->
            <script type="text/html" id="table-toolbar">
                <div class="layui-btn-container">
                    <button class="layui-btn layui-btn-xs" lay-event="up">上架</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="down">下架</button>
                    <button class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</button>
                    <button class="layui-btn layui-btn-xs" lay-event="async">媒资同步</button>
                    <button class="layui-btn layui-btn-xs  layui-btn-danger" lay-event="clearTag">清空标签</button>
                    <button class="layui-btn layui-btn-xs" lay-event="update">批量设置(覆盖)</button>
                    <button class="layui-btn layui-btn-xs" lay-event="update-overlay">批量设置(叠加)</button>
                    <button class="layui-btn layui-btn-xs" lay-event="update-remove">批量设置(移除)</button>
                    <button class="layui-btn layui-btn-xs layui-btn-primary" lay-event="es">刷新索引</button>
                    <button class="layui-btn layui-btn-xs layui-btn-primary" lay-event="sign">运营签到</button>
                </div>
            </script>
            <!-- 数据表格-行工具条 -->
            <script type="text/html" id="table-item-toolbar">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="comment">评论</a>
            </script>
        </div>
    </div>
</div>
<script>
    var layerIndex, layer, util, table, form, $;
    layui.use(['layer', 'form', 'table', 'admin'], function () {
        $ = layui.jquery;
        layer = layui.layer;
        form = layui.form;
        table = layui.table;
        util = layui.util;

        /*初始化表格*/
        table.render({
            elem: '#table'
            , url: location.href
            , method: "post"
            , where: form.val("searchForm")
            , skin: 'line'
            , size: 'sm' //小尺寸的表格
            , toolbar: '#table-toolbar'
            , request: {
                limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            , page: {
                layout: ['prev', 'page', 'next', 'skip', 'count', 'limit']
                , curr: 1 //设定初始在第 1 页
                , groups: 6 //只显示 5 个连续页码
                , first: '首页'
                , last: '尾页'
                , limit: 30
                , limits: [10, 30, 50, 100]
            }
            , parseData: function (res) { //res 即为原始返回的数据
                return res;
            }
            , cols: [[
                {type: 'checkbox'}
                , {field: '_id', title: 'ID', width: 120, align: 'left'}
                , {
                    field: 'name', title: '名称', templet: function (row) {
                        return '名称: ' + row.name + "<br/>" + '别名: ' + row.alias_name;
                    }, align: 'left'
                }
                , {
                    field: 'img_x', title: '封面', width: 80, templet: function (row) {
                        if (row.img_x) {
                            var link = '<?php echo $mediaUrl;?>' + row.img_x;
                            return '<a target="_blank" href="' + link + '" ><img src="' + link + '" onmouseout="hideImg(this)" onmouseover="showImg(this)" class="table-tips-img" style="max-width: 60px;max-height: 35px"/></a>'
                        }
                        return '-';
                    }, align: 'center'
                }
                , {field: 'cat_id', title: '分类', width: 60, align: 'center'}
                , {field: 'tags', title: '标签', align: 'left'}
                , {
                    field: 'pay_type', title: '购买类型', width: 80, align: 'center', style: 'color:red', templet: function (row) {
                        if (row.pay_type == 'money') {
                            return row.pay_type + " ￥:" + row.money;
                        }
                        return row.pay_type;
                    }
                }
                , {field: 'comment', title: '评论', width: 50, align: 'center', sort: true}
                , {field: 'real_click', title: '点击', width: 50, align: 'center', sort: true}
                , {field: 'real_love', title: '点赞', width: 50, align: 'center', sort: true}
                , {field: 'real_favorite', title: '收藏', width: 50, align: 'center', sort: true}
                , {field: 'favorite_rate', title: '收藏率', width: 60, align: 'center', sort: true}
                , {field: 'sort', title: '排序', width: 70, align: 'center', sort: true}
                , {field: 'icon', title: '图标', width: 50, align: 'center'}
                , {field: 'status', title: '状态', width: 50, align: 'center'}
                , {
                    field: 'update_date', title: '更新', width: 120, align: 'left', templet: function (row) {
                        return '更新表:' + row.update_date + "<br/>" + '更新状态:' + row.update_status + '<br/>最后更新:' + row.last_update;
                    }
                }
                , {field: 'chapter_count', title: '章节数', width: 50, align: 'center'}
                , {field: 'show_at', title: '上架时间', width: 100, align: 'center', sort: true}
                , {field: 'created_at', title: '创建时间', align: 'center', width: 100, sort: true}
                , {title: '操作', toolbar: '#table-item-toolbar', align: 'center', width: 120}
            ]],
        });
        /*表格搜索事件*/
        form.on('submit(searchFormBtn)', function (obj) {
            table.reload('table', {where: obj.field, page: {curr: 1}});
            return false;
        });
        /*表格排序事件*/
        table.on('sort(table)', function (obj) {
            var order = obj.type === 'asc' ? 1 : -1;
            table.reload('table', {initSort: obj, where: {sort: obj.field, order: order}});
        });

        /*表格-顶部工具条事件*/
        table.on('toolbar(table)', function (obj) {
            var checkStatus = table.checkStatus(obj.config.id);
            var data = checkStatus.data;
            var ids = new Array();
            for (var index = 0; index < data.length; index++) {
                ids.push(data[index]._id)
            }
            switch (obj.event) {
                case 'async':
                    asyncRow();
                    break;
                case 'up':
                    doRow(ids, 'up');
                    break;
                case 'update':
                    updateRow(ids);
                    break;
                case 'update-overlay':
                    updateOverlayRow(ids);
                    break;
                case 'update-remove':
                    updateRemoveRow(ids);
                    break;
                case 'clearTag':
                    doRow(ids, 'clearTag');
                    break;
                case 'es':
                    doRow(ids, 'es');
                    break;
                case 'down':
                    doRow(ids, 'down');
                    break;
                case 'del':
                    doRow(ids, 'del');
                    break;
                case 'sign':
                    doAdminSign();
                    break;
            }
        });
        /*表格-行事件*/
        table.on('tool(table)', function (obj) {
            var data = obj.data;
            switch (obj.event) {
                case 'edit':
                    layerIndex = layer.open({
                        type: 2,
                        content: "<?php echo createUrl('/comics/detail'); ?>?_id=" + data._id,
                        area: ['90%', '90%']
                    });
                    break;
                case 'del':
                    var ids = new Array();
                    ids.push(data._id);
                    doRow(ids, 'del');
                    break;
                case 'comment':
                    layerIndex = layer.open({
                        type: 2,
                        content: "<?php echo url()->get('/comment/list'); ?>?object_type=comics&object_id=" + data._id,
                        area: ['90%', '80%']
                    });
                    break;
                case 'danmu':
                    layerIndex = layer.open({
                        type: 2,
                        content: "<?php echo url()->get('/danmaku/list'); ?>?object_type=comics&object_id=" + data._id,
                        area: ['90%', '80%']
                    });
                    break;
            }
        });

        //监听其他事件
        util.event('lay-active', {
            tag: function (e) {
                var isSelected = !e.hasClass('layui-btn-primary');
                if (isSelected) {
                    e.addClass('layui-btn-primary');
                    $("#tag").val('');
                    return;
                }
                $('.layui-btn-sm-tag').addClass('layui-btn-primary');
                e.removeClass('layui-btn-primary');
                $("#tag").val(e.attr('data-id'));
            },
            reset: function (e) {
                $('.layui-btn-sm-tag').addClass('layui-btn-primary');
                $('.layui-btn-sm-tag-all').removeClass('layui-btn-primary');
                $("#tag").val('');
            },
        });


        //同步
        function asyncRow() {
            layerIndex = layer.open({
                title: '媒资库漫画同步',
                type: 2,
                shade: 0.8,
                content: "<?php echo url()->get('/comics/widget'); ?>?type=async",
                area: ['80%', '80%'],
            });
        }


        function doRow(ids, act) {
            if (ids == null || ids.length < 1) {
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            showConfirmMsg("确定操作吗?", function () {
                var loadIndex = layer.load(0, {time: 30 * 1000});
                doAjax("<?php echo createUrl('/comics/do')?>", {act: act, id: ids.join(",")}, function (res) {
                    layer.close(loadIndex);
                    if (res.status == 'y') {
                        showSuccessMsg("操作成功!");
                        table.reload('table');
                    } else {
                        showErrorMsg(res.error);
                    }
                });
            });
        }

        //批量设置
        function updateRow(ids) {
            ids = ids.join(',');
            if (ids == null || ids.length < 1) {
                showErrorMsg("请选择需要的数据!");
                return false;
            }
            layerIndex = layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo createUrl('/comics/update'); ?>?ids=" + ids,
                area: ['90%', '80%'],
            });
        }

        // 批量叠加设置
        function updateOverlayRow(ids) {
            ids = ids.join(',');
            layerIndex = layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo url()->get('/comics/update-overlay'); ?>?ids=" + ids,
                area: ['85%', '80%'],
            });
        }


        function updateRemoveRow(ids) {
            ids = ids.join(',');
            layerIndex = layer.open({
                type: 2,
                shade: 0.8,
                content: "<?php echo url()->get('/comics/update-remove'); ?>?ids=" + ids,
                area: ['85%', '80%'],
            });
        }
    })
</script>
